services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    restart: on-failure
  frontend:
    build:
      context: ../../frontend
    ports:
      - 4200:80
    restart: on-failure
  backend:
    build:
      context: ../../backend
    ports:
      - 8080:80